import Head from 'next/head'
import styles from './styles.module.css'
import Slider from "react-slick";
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import { GrPrevious, GrNext } from 'react-icons/gr'
import CardPodcastCarousel from '../../components/CardPodcastCarousel';
import { podcasts } from "../../constants/data/podcasts"

export default function Home() {

  const SlickArrowLeft = ({ currentSlide, slideCount, ...props }) => (
    <GrPrevious {...props}/>

  );

  const SlickArrowRight = ({ currentSlide, slideCount, ...props }) => (
    <GrNext {...props}/>
  );

  const settings = {
    dots: false,
    infinite: false,
    speed: 500,
    slidesToShow: 2,
    slidesToScroll: 1,
    prevArrow: <SlickArrowLeft />,
    nextArrow: <SlickArrowRight />,
    
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}> Destaque</h2>
        <div className={styles.carousel}>
            <Slider {...settings}>
                {podcasts.map((podcast) => (
                    <CardPodcastCarousel 
                        key={podcast.id} 
                        title={podcast.title}
                        url={podcast.url} 
                        description={podcast.description}
                    />
                ))}
            </Slider>
        </div>

        
      </main>


    </div>
  )
}
